homepage/homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls'))
    #path('projects/', include('projects.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

homepage/projects/urls.py
from django.urls import path
from . import views
app_name = 'projects'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('projects/<int:pk>/', views.DetailView.as_view(), name='detail'),
]

homepage/projects/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Project(models.Model):
    # 사진 ImageField(upload_to=None, height_field=None, width_field=None, max_length=100, **options)참
    image = models.ImageField(default="", blank=True)
    # 파일업로드
    file = models.FileField(upload_to='uploads', default="", blank=True)

    project_title = models.CharField(max_length=100)         # 프로젝트 제목
    project_shorten = models.TextField(default="", max_length=100)                     # 프로젝트 간략설명(2줄 이내)
    project_text = models.TextField()                        # 프로젝트 상세설명
    project_date = models.DateField('Date Finished')         # 프로젝트 날짜
    project_member = models.TextField(default="No one")      # 멤버 이름
    project_extra = models.TextField(default="", blank=True) # 기타정보
    project_year_semester = models.TextField()               # 년도-학기
    project_year = models.TextField()                        # 년도

    def project_year_semester(self):
        if self.project_date.month >= 1 & self.project_date.month <= 6:
            semester = 1
        elif self.project_date.month >= 7 & self.project_date.month <= 12:
            semester = 2
        else:
            semester = 3
        return str(self.project_date.year) + '-' + str(semester)

    def project_year(self):
        return str(self.project_date.year)

    def publish(self):
        self.project_date = timezone.now()
        self.save()

    def __str__(self):
        return self.project_title

homepage/projects/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Project
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'projects/index.html'
    # context_object_name = 'latest_project_list'
    context_object_name = 'object_list'

    def get_queryset(self):
        return Project.objects.order_by('project_date')

    def get_context_data(self, **kwargs):
        # et = super(IndexView, self).get_context_data(**kwargs)
        context = super().get_context_data(**kwargs)

        projects = Project.objects.order_by('project_date')

        context['years'] = [x for x in range(projects.first().project_date.year, projects.last().project_date.year + 1)][::-1]
        return context

class DetailView(generic.DetailView):
    model = Project
    template_name = 'projects/detail_context.html'

homepage/projects/templates/projects/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static '/projects/style.css' %}">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <link rel="icon" href="{% static '/projects/images/favicon-font.png' %}" sizes="16x16">
        <title>PYNEER</title>
    </head>

    <body>
        <div class="header">
            <div class="l-wrapper">
                <div class="header-logo detail"><a href="{% url 'projects:index' %}"><img src="{% static '/projects/images/logo.svg' %}"></a>
            </div>
                <span class="back"><a href="{% url 'projects:index' %}">&#8672;</a></span>
            </div>
        </div>

        <div class="page-container">
          {% block content %}
          {% endblock %}
        </div>
    </body>
</html>

homepage/projects/templates/projects/detail_context.html
{% extends 'projects/detail.html' %}
{% load staticfiles %}
{#로드 스테틱파일을 하는 이유는 아래에 이미지를 사용하기 때문이다.#}
{#사진을 업로드 할 수 있는 방법을 적용한다면 이에 대한 수정이 필요하다.#}
{% block content %}

<section class="page-project">
    <div class="project-ty">
        <span class="border"> </span>
        <div class="project-ty__title"><h2>{{ project.project_title }}</h2></div>
        <div class="project-ty__year">{{ project.project_year }}</div>
        <div class="project-ty__member">{{ project.project_member }}</div>
    </div>
    <div class="project-info">
        <div class="project-info__desc">
            <p>{{ project.project_text|linebreaksbr }}</p>
        </div>
    </div>
    <div class="project-images">
        <!--디테일에서 사진 불러오는 코드-->
        {% if project.image %}
        <img src="{{ project.image.url }}">
        {% else %}
        {% endif %}
    </div>
    <div class="project-external">
        {{ project.project_extra }}
    </div>
    {% if project.file %}
        <div>
        <a href="{{ project.file.url }}">Download file</a>
        </div>
    {% else %}
    {% endif %}


</section>
{% endblock %}

homepage/projects/templates/projects/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="keywords" content="성균관대학교, 파이니어, pyneer, 성균관대학교 파이니어, 성균관대학교 프로그래밍 동아리">
        <meta name="description" content="성균관대학교 프로그래밍 동아리 pyneer 입니다">
        <meta name="author" content="pyneer">

        <link rel="stylesheet" href="{% static '/projects/style.css' %}">
        <!--여기에 '/project'라고 하니까 안됐었다. 대체 왜??? -->

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

        <link rel="icon" href="{% static '/projects/images/favicon-font.png' %}" sizes="16x16">

        <title>PYNEER</title>
    </head>

    <body>
      <!-- HEADER NAVIGATION MENU -->
       <div class="arrow-up">&uarr;</div>
        <div class="header">
            <div class="l-wrapper">
                <div class="header-logo" href="#"><a href="{% url 'projects:index' %}"><img src="{% static '/projects/images/logo.svg' %}"></a></div>
                <ul class="header-menu">
                    <li><a class="active" href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Project</a></li>
                    <li><a href="#">Contact</a></li>

                </ul>
            </div>
        </div>
        <!-- hamburger menu for mobile -->
        <input type="checkbox" class="menu-box" id="menu-control" />
        <label class="menu-button" for="menu-control">
            <span class="line"></span>
            <span class="line"></span>
            <span class="line"></span>
        </label>
        <div class="header-menu-mobile">
            <li><a class="active" href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Project</a></li>
            <li style="border-bottom: 1px solid black"><a href="#">Contact</a></li>
        </div>

        <!-- INTRO -->
        <div class="section intro">
            <div class="container">
                <div class="card">
                    <div class="front">
                        <div class="title-skku">성균관대학교 <br class="br-on-mobile">프로그래밍 동아리<br></div><div class="title-pyneer">Pyneer<br></div>
                    </div>
                    <div class="back">
                        <div class="back-content">
                            <p>Pyneer에서는 서로 다른 분야의 학생들이 모여 각자가 알고 있는 전공 지식을<br>서로에게 가르치고 배우면서 사고의 스펙트럼을 넓힙니다.<br>새로운 아이디어를 구체화하고 제작하면서 실질적인 프로그래밍에 대한 이해도 키우고,<br>구체적인 팀 경험을 통해 협업하는 환경에서 성장하는 기회를 제공합니다.</p>
                        </div>
                    </div>
                </div>
            </div>
            <!--            <canvas width="1000" height="400"></canvas>-->
        </div>

        <!-- ABOUT -->
        <div class="section about">
            <div class="container">
                <h2>About us</h2><span class="border">&nbsp;</span>
                <ul class="l-row">
                    <li class="l-col l-col-6-12">
                        <div class="part">
                            <h3 class="part-title"><span class="number">01.</span><br>프로젝트 개발</h3>
                            <p>Pyneer에서는 실제 문제를 해결하기 위한 프로젝트 활동을 통해서 살아있는 프로그래밍 역량을 키웁니다.
                                Python, C++, JAVA 등 다양한 프로젝트 유형을 진행하고 있으며,
                                전공 구분 없이 자신이 배운 프로그래밍을 통해 아이디어를 실현하고 싶은 분이면 누구나 환영합니다.
                                <br>학회는 명륜 캠퍼스와 율전 캠퍼스가 합쳐서 운영되며,
                                주 1회 이상 오프라인 회의를 가집니다. 또한 한 학기에 2회 정도 캠퍼스 통합 모임이 있습니다.</p>
                        </div>
                    </li>
                    <li class="l-col l-col-6-12">
                        <div class="part right">
                            <h3 class="part-title"><span class="number">02.</span><br>스터디 운영</h3>
                            <p>다양한 전공분야와 배경지식을 가진 학생들이 아이디어를 도출하고 협업하는 팀 문화 속에서 각자 부족한 부분에 맞는 스터디를 진행합니다.</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <!-- PROJECT -->
        <div class="section project">
            <div class="container-desktop">
                <h2>Project</h2><span class="border">&nbsp;</span>
                <table>
                    {% for y in years %}
                    <tr>
                        <th class="project-year">
                            <h2>{{ y }}</h2>
                        </th>
                        {% for p in object_list %}
                            {% if p.project_date.year == y %}
                        <td onclick="window.location='{% url 'projects:detail' p.id %}'">
                            <div class="proj circle">
                                <div class="desc">
                                    <div class="desc-title">
                                        <a href="{% url 'projects:detail' p.id %}">{{ p.project_title }}</a>
                                    </div>
                                    <div class="content">
                                        {{ p.project_shorten }}
                                    </div>
                                    {% endif %}
                                </div>

                                {% endfor %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="container-mobile">
                <h2 class="mobile">&nbsp;Project</h2>
                <div class="wrap-drop">
                    <h3 class="project-year">2016</h3>
                    <ul class="drop">
                        <li class="selected"><div class="proj"><a>프로젝트1</a></div></li>
                    </ul>
                </div>
                <div class="wrap-drop">
                    <h3 class="project-year">2017</h3>
                    <ul class="drop">
                        <li class="selected"><div class="proj"><a>프로젝트1</a></div></li>
                        
                        <div class="proj"><li><a>프로젝트4</a></li></div>
                    </ul>
                </div>
                <div class="wrap-drop">
                    <h3 class="project-year">2018</h3>
                    <ul class="drop">
                        <li class="selected"><div class="proj"><a>프로젝트1</a></div></li>
                        <li><div class="proj"><a>프로젝트2</a></div></li>
                        <li><div class="proj"><a>프로젝트3</a></div></li>
                        <li><div class="proj"><a>프로젝트4</a></div></li>
                    </ul>
                </div>
            </div>
        </div>



        <div class="section contact">
            <h3>Contact</h3>
            <p>pyneer2016@gmail.com</p>
        </div>

        <script type="text/javascript" src="{% static 'projects/script.js' %}"></script>
    </body>

</html>